import type { Battle } from "@tweetbattle402/shared";

export const demoBattles: Battle[] = [
  {
    id: 402,
    challenger: "0x71a8...29c1",
    opponent: "0x93b2...10ef",
    challengerHandle: "chainpoet",
    opponentHandle: "rollupmaxi",
    topic: "Does Monad make general-purpose L2s obsolete?",
    stakeAmount: "12",
    tweetsPerPlayer: 3,
    status: "Active",
    endTime: Date.now() + 1000 * 60 * 48,
    votingEndTime: Date.now() + 1000 * 60 * 108,
    aiWeightBps: 3000,
    challengerVotePower: 34,
    opponentVotePower: 27,
    votePool: "8.42",
  },
  {
    id: 405,
    challenger: "0x8aa0...9d31",
    opponent: "",
    challengerHandle: "bytebard",
    opponentHandle: "cryptocritic",
    topic: "Are memecoins useful coordination primitives?",
    stakeAmount: "5",
    tweetsPerPlayer: 2,
    status: "PendingAcceptance",
    endTime: Date.now() + 1000 * 60 * 60 * 18,
    votingEndTime: 0,
    aiWeightBps: 3000,
    challengerVotePower: 0,
    opponentVotePower: 0,
    votePool: "0",
  },
  {
    id: 399,
    challenger: "0x39f0...1a22",
    opponent: "0xe901...fa02",
    challengerHandle: "proofplease",
    opponentHandle: "anonallocator",
    topic: "Should onchain governance remain token-weighted?",
    stakeAmount: "20",
    tweetsPerPlayer: 3,
    status: "Finalized",
    endTime: Date.now() - 1000 * 60 * 120,
    votingEndTime: Date.now() - 1000 * 60 * 60,
    aiWeightBps: 3000,
    challengerVotePower: 52,
    opponentVotePower: 79,
    votePool: "17.8",
  },
];

export const demoTweets = [
  {
    side: "challenger",
    type: "Opening Argument",
    handle: "chainpoet",
    text: "Execution speed is not a feature at the margin. It changes what developers can build without fragmenting state or forcing users through bridges.",
    url: "https://x.com/chainpoet/status/1930212345678901234",
  },
  {
    side: "opponent",
    type: "Opening Argument",
    handle: "rollupmaxi",
    text: "Throughput alone does not erase the distribution, customization, and sovereignty advantages of purpose-built rollups.",
    url: "https://x.com/rollupmaxi/status/1930212345678901288",
  },
] as const;
